# Generated by Django 3.1 on 2020-08-11 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
