# Generated by Django 3.1 on 2020-08-09 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rp_name', models.CharField(max_length=100)),
                ('badge', models.CharField(max_length=100)),
            ],
        ),
    ]
