# Generated by Django 3.1 on 2020-08-14 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rp_name', models.CharField(max_length=30)),
                ('rp_service_number', models.IntegerField()),
                ('badge', models.CharField(max_length=30)),
                ('strip', models.CharField(max_length=30)),
                ('rank', models.CharField(max_length=30)),
            ],
        ),
    ]
