# Generated by Django 3.1 on 2020-09-07 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='license_key',
            field=models.CharField(default=True, max_length=12, primary_key=True, serialize=False),
        ),
    ]
