# Generated by Django 3.1 on 2020-09-17 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Strip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strip_name', models.CharField(max_length=30, unique=True)),
            ],
        ),
    ]
